sudo: false
language: node_js

cache:
  directories:
    - node_modules/

install:
  - yarn

script:
  - yarn test

after_script:
  - cat coverage/lcov.info | coveralls

branches:
  only:
    - master
